In [2]:
import torch

### 2.2.1 创建tensor
tensor是一个多维数组，在pytorch中有很多创建方法，我把它分为常用形式，通过数据创建，现有tensor创建，随机形式创建
![attributes](./assets/pic/tensor_attributes.png)


#### 2.2.1.1 常用形式创建

- 未初始化形式

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


- 创建5 × 3的long型全0的tensor

In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


- 以及类似的全1 ones， 对角线为1 eye

In [8]:
x = torch.ones(5,3)
print(x)
x = torch.eye(5,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


#### 2.2.1.2 通过数据创建

- 直接通过数据创建

In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


- 通过numpy数组创建
    通过from_numpy函数或者直接使用大写的Tensor构造函数创建

In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [14]:
import numpy as np 
a = np.ones(5)
b = torch.Tensor(a)
c = torch.LongTensor(a)#可以直接使用类型构造函数也可以使用dtype属性
print(a, b, c)
d = b.numpy()# 可以返回成numpy 数组
print(a, b, c, d)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.]) tensor([1, 1, 1, 1, 1])
[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.]) tensor([1, 1, 1, 1, 1]) [1. 1. 1. 1. 1.]


- 所有在CPU上的 Tensor （除了 CharTensor ）都⽀持与NumPy数组相互转换。
此外上⾯提到还有⼀个常⽤的⽅法就是直接⽤ torch.tensor() 将NumPy数组转换成 Tensor ，需要
注意的是该⽅法总是会进⾏数据拷⻉，返回的 Tensor 和原来的数据不再共享内存

In [15]:
c = torch.tensor(a)
a += 1
print(a, c)

[2. 2. 2. 2. 2.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


#### 2.2.1.3 通过现有tensor创建
还可以通过现有的 Tensor 来创建，此⽅法会默认᯿⽤输⼊ Tensor 的⼀些属性，例如数据类型，除⾮
⾃定义数据类型
-new_ones(), randn_like() 后面带有new 或者like的函数

In [16]:
x = torch.ones(5, 3)
x = x.new_ones(5, 3, dtype=torch.float64)# 返回的tensor默认具有相同的
torch.dtype和torch.device
print(x)
x = torch.randn_like(x, dtype=torch.float)# 指定新的数据类型
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0303,  2.0638, -0.2442],
        [-0.2605, -0.6409, -0.7998],
        [-0.1893, -0.7228, -0.0306],
        [-0.5937, -0.0340, -1.4261],
        [-0.2194, -0.0731,  0.4138]])


#### 2.2.1.4 其他方法
![init](./assets/pic/tensor_init.png)

#### 2.2.1.5 常用属性
- 我们可以通过 shape 或者 size() 来获取 Tensor 的形状:


In [18]:
print(x.size())
print(x.shape)
#注意：返回的torch.Size其实就是⼀个tuple, ⽀持所有tuple的操作

torch.Size([5, 3])
torch.Size([5, 3])
