In [2]:
import torch

### 2.2.1 创建tensor
tensor是一个多维数组，在pytorch中有很多创建方法，我把它分为常用形式，通过数据创建，现有tensor创建，随机形式创建
![attributes](./assets/pic/tensor_attributes.png)


#### 2.2.1.1 常用形式创建

- 未初始化形式

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


- 创建5 × 3的long型全0的tensor

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


- 以及类似的全1 ones， 对角线为1 eye

In [5]:
x = torch.ones(5,3)
print(x)
x = torch.eye(5,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


#### 2.2.1.2 通过数据创建

- 直接通过数据创建

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


- 通过numpy数组创建
    通过from_numpy函数或者直接使用大写的Tensor构造函数创建

In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [14]:
import numpy as np 
a = np.ones(5)
b = torch.Tensor(a)
c = torch.LongTensor(a)#可以直接使用类型构造函数也可以使用dtype属性
print(a, b, c)
d = b.numpy()# 可以返回成numpy 数组
print(a, b, c, d)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.]) tensor([1, 1, 1, 1, 1])
[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.]) tensor([1, 1, 1, 1, 1]) [1. 1. 1. 1. 1.]


- 所有在CPU上的 Tensor （除了 CharTensor ）都⽀持与NumPy数组相互转换。
此外上⾯提到还有⼀个常⽤的⽅法就是直接⽤ torch.tensor() 将NumPy数组转换成 Tensor ，需要
注意的是该⽅法总是会进⾏数据拷⻉，返回的 Tensor 和原来的数据不再共享内存

In [15]:
c = torch.tensor(a)
a += 1
print(a, c)

[2. 2. 2. 2. 2.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


#### 2.2.1.3 通过现有tensor创建
还可以通过现有的 Tensor 来创建，此⽅法会默认᯿⽤输⼊ Tensor 的⼀些属性，例如数据类型，除⾮
⾃定义数据类型
-new_ones(), randn_like() 后面带有new 或者like的函数

In [16]:
x = torch.ones(5, 3)
x = x.new_ones(5, 3, dtype=torch.float64)# 返回的tensor默认具有相同的
torch.dtype和torch.device
print(x)
x = torch.randn_like(x, dtype=torch.float)# 指定新的数据类型
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0303,  2.0638, -0.2442],
        [-0.2605, -0.6409, -0.7998],
        [-0.1893, -0.7228, -0.0306],
        [-0.5937, -0.0340, -1.4261],
        [-0.2194, -0.0731,  0.4138]])


#### 2.2.1.4 其他方法
![init](./assets/pic/tensor_init.png)

#### 2.2.1.5 常用属性
- 我们可以通过 shape 或者 size() 来获取 Tensor 的形状:


In [18]:
print(x.size())
print(x.shape)
#注意：返回的torch.Size其实就是⼀个tuple, ⽀持所有tuple的操作

torch.Size([5, 3])
torch.Size([5, 3])


### 2.2.2 操作


#### 算术操作
以加法为例 有三种形式
- 重载运算符

In [ ]:
y = torch.rand(5,3)
print(x + y)

Error: Error: Activating Python 3.5.2 64-bit to run Jupyter failed with Error: Command failed: . /raid/home/zhaochao/.pyenv/shims/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /raid/home/zhaochao/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/printEnvVariables.py
pyenv-virtualenv: version `system' is not a virtualenv
.

- 加法函数

In [ ]:
print(torch.add(x, y))

Error: Error: Activating Python 3.5.2 64-bit to run Jupyter failed with Error: Command failed: . /raid/home/zhaochao/.pyenv/shims/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /raid/home/zhaochao/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/printEnvVariables.py
pyenv-virtualenv: version `system' is not a virtualenv
.

指定输出

In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

Error: Error: Activating Python 3.5.2 64-bit to run Jupyter failed with Error: Command failed: . /raid/home/zhaochao/.pyenv/shims/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /raid/home/zhaochao/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/printEnvVariables.py
pyenv-virtualenv: version `system' is not a virtualenv
.

- 原地操作

In [ ]:
y.add_(x)
print(y)

Error: Error: Activating Python 3.5.2 64-bit to run Jupyter failed with Error: Command failed: . /raid/home/zhaochao/.pyenv/shims/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /raid/home/zhaochao/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/printEnvVariables.py
pyenv-virtualenv: version `system' is not a virtualenv
.

#### 2.2.2.2 索引
使用类似numpy的索引操作来访问Tensor的一部分。注意的是索引出来的结果与原内存共享内存。



In [ ]:
y = x[0, :]
y += 1
print(y)
print(x[0, :])

Error: Error: Activating Python 3.5.2 64-bit to run Jupyter failed with Error: Command failed: . /raid/home/zhaochao/.pyenv/shims/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /raid/home/zhaochao/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/printEnvVariables.py
pyenv-virtualenv: version `system' is not a virtualenv
.

#### 2.2.2.3 改变形状

In [ ]:
y = x.view(15)
z = x.view(-1, 5)
print(x.size(), y.size(), z.size())

Error: Error: Activating Python 3.5.2 64-bit to run Jupyter failed with Error: Command failed: . /raid/home/zhaochao/.pyenv/shims/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /raid/home/zhaochao/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/printEnvVariables.py
pyenv-virtualenv: version `system' is not a virtualenv
.

注意view() 返回的新tensor与源tensor共享内存（其实是同.一个tensor），也即更更改其中的.一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了了对这个张量量的观察.角度)
如果想要一个新的副本先copy再view。

#### 2.2.2.4 线性代数

### 2.2.3 广播机制

对两个形状不同的Tensor做按元素运算可能会触发广播机制：将两个tensor通过复制元素使其形状相同再按元素运算.仅限按元素运算的可以通过复制变成一样的。

In [ ]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

Error: Error: Activating Python 3.5.2 64-bit to run Jupyter failed with Error: Command failed: . /raid/home/zhaochao/.pyenv/shims/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /raid/home/zhaochao/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/printEnvVariables.py
pyenv-virtualenv: version `system' is not a virtualenv
.

### 2.2.4 运算的内存开销

前面说了，索引、view是不会开辟新内存的，而像y = x + y这样的运算是会新开内存的，然后将y指向新内存。有两种方式可以避免这种内存开销
- 使用y[:]

In [ ]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before) # True

Error: Error: Activating Python 3.5.2 64-bit to run Jupyter failed with Error: Command failed: . /raid/home/zhaochao/.pyenv/shims/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /raid/home/zhaochao/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/printEnvVariables.py
pyenv-virtualenv: version `system' is not a virtualenv
.

- 使用运算全名函数汇总的out参数或者+= 或add_这种inplace操作

In [ ]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before) # True


Error: Error: Activating Python 3.5.2 64-bit to run Jupyter failed with Error: Command failed: . /raid/home/zhaochao/.pyenv/shims/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /raid/home/zhaochao/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/printEnvVariables.py
pyenv-virtualenv: version `system' is not a virtualenv
.

### 2.2.5 Tensor on GPU

两种方式，设置device参数或者使用to函数

In [ ]:
# ..............PyTorch GPU..............
if torch.cuda.is_available():
device = torch.device("cuda") # GPU
y = torch.ones_like(x, device=device) # ..............GPU....
Tensor
x = x.to(device) # ...... .to("cuda")
z = x + y
print(z)
print(z.to("cpu", torch.double)) # to()......................


Error: Error: Activating Python 3.5.2 64-bit to run Jupyter failed with Error: Command failed: . /raid/home/zhaochao/.pyenv/shims/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /raid/home/zhaochao/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles/printEnvVariables.py
pyenv-virtualenv: version `system' is not a virtualenv
.